name: fogosmobile
description: Fogos.pt new iOS and Android app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sentry: any
  cupertino_icons: ^0.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  flutter_map: ^0.8.0
  http: ^0.12.0
  dio: ^2.1.7
  firebase_messaging: ^6.0.9
  shared_preferences: ^0.4.3
  diacritic: ^0.1.1
  url_launcher: ^5.0.2
  flutter_markdown: ^0.2.0
  auto_size_text: 1.1.2
  
  share: ^0.6.1+1

  #ui
  flutter_svg: ^0.15.0
  modal_progress_hud: ^0.1.3
  charts_flutter: ^0.8.1

  #localizations
  intl: ^0.16.0
  intl_translation: ^0.17.7


dev_dependencies:
  cached_network_image: 2.0.0-rc
  build_runner: ^1.2.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/
  - assets/partners/